# Sane default
setopt no_beep
setopt auto_cd
export HISTSIZE=1000000
export SAVEHIST=1000000
setopt append_history
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt share_history

# Envvars
export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export PATH="/usr/local/bin:${HOME}/usr/local/bin:/usr/local/sbin:${PATH}"

# Packages
source ${HOME}/.zplug/init.zsh
zplug "zsh-users/zsh-history-substring-search"
zplug "zsh-users/zsh-autosuggestions"
zplug "changs/slimzsh"

# Minimal settings
export PURE_PROMPT_SYMBOL='> '
source ${HOME}/.zsh-autosuggestions/zsh-autosuggestions.zsh
source ${HOME}/.slimzsh/slim.zsh
unsetopt correct_all

# Theming
eval $(dircolors -b ${HOME}/.dir_colors)
if [ -n "$LS_COLORS" ]; then
    zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
fi

# Aliases
alias ls='ls --color=auto'
alias ll='ls -lh'
alias la='ls -alh'

# Keys, Completions
bindkey -e
bindkey "\e[Z" reverse-menu-complete
bindkey -a 'q' push-line
bindkey -a 'H' run-help
autoload history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey "^P" history-beginning-search-backward-end
bindkey "^N" history-beginning-search-forward-end

# Miniconda3
function use-conda(){
	. "${HOME}/miniconda3/etc/profile.d/conda.sh"
}

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
