#
# Executes commands at login pre-zshrc.
#
## Envvars
export SHELL=/usr/local/bin/zsh
export EDITOR='vim'
export VISUAL='code'
export PAGER='less'
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8

export PGDATA="/usr/local/var/postgres"
export GOPATH="${HOME}/repos/gopher"
[ -n "$GOPATH" ] && export PATH="${PATH}:$(go env GOPATH)/bin"

