#
# Defines environment variables.
#

export PATH="/usr/local/bin:${HOME}/usr/local/bin:/usr/local/sbin:${PATH}"
export PATH="${PATH}:/usr/local/opt/go/libexec/bin"
export PATH="${HOME}/.cargo/bin:${PATH}"
export JAVA_HOME="$(/usr/libexec/java_home -v 1.8)"

[ -d "${HOME}/.pyenv" ] && eval "$(pyenv init -)"
