# Sane default
unsetopt correct_all
setopt no_beep
setopt auto_cd
export HISTFILE=~/.zsh_history
export HISTSIZE=1000000
export SAVEHIST=1000000
setopt append_history
setopt extended_history
setopt hist_ignore_dups # ignore duplication command history list
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_verify
setopt share_history
setopt inc_append_history
setopt hist_expire_dups_first
setopt no_auto_remove_slash
setopt interactivecomments
unsetopt menu_complete   # do not autoselect the first completion entry
unsetopt flowcontrol
setopt auto_menu         # show completion menu on succesive tab press
setopt complete_in_word
setopt always_to_end
stty stop undef
stty start undef
export WORDCHARS='*?_-.[]~=&;!#$%^(){}<>'

# Minimal settings
source ${HOME}/.zplug/init.zsh

# Packages
zplug "b4b4r07/emoji-cli"
zplug "zsh-users/zsh-completions"
zplug "mafredri/zsh-async", from:github
zplug "sindresorhus/pure", use:pure.zsh, from:github, as:theme
zplug "zsh-users/zsh-syntax-highlighting", defer:2

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

fpath+=~/.zfunc

# Then, source plugins and add commands to $PATH
zplug load
autoload -U compinit && compinit

# Theming
[ -f "${HOME}/.nord.dircolors" ] && eval $(gdircolors -b ${HOME}/.nord.dircolors)
[ -n "$LS_COLORS" ] && zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

# Aliases
alias ls='gls -h --color=auto'
alias ll='ls -lh'
alias la='ls -alh'
alias chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"

# Keys, Completions
bindkey -e
bindkey "\e[Z" reverse-menu-complete
bindkey -a 'q' push-line
bindkey -a 'H' run-help
bindkey "^F" forward-char
bindkey "^B" backward-char
autoload history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey "^P" history-beginning-search-backward-end
bindkey "^N" history-beginning-search-forward-end

use-google-cloud-sdk() {
    _google_cloud_sdk_dir="${HOME}/google-cloud-sdk/"
    [ -f "${_google_cloud_sdk_dir}path.zsh.inc" ] && source "${_google_cloud_sdk_dir}path.zsh.inc"
    [ -f "${_google_cloud_sdk_dir}completion.zsh.inc" ] && source "${_google_cloud_sdk_dir}completion.zsh.inc"
    pyenv global 3.7.2 2.7.15 system
}

use-google-cloud-sdk

eval "$(pyenv init -)"
export PATH="${HOME}/.poetry/bin:${PATH}"
# Fix for https://github.com/sdispater/poetry/issues/571 (poetry <= 0.12.*)
alias poetry_shell=$'source "$(dirname $(poetry run which python))/activate"'

[ -f "${HOME}/.fzf.zsh" ] && . ${HOME}/.fzf.zsh

