#
# Executes commands at login pre-zshrc.
#
#
_byobu_sourced=1 . /usr/bin/byobu-launch 2>/dev/null || true

# Run dockerd
sudo service docker status &>/dev/null || sudo service docker start &>/dev/null 

# X11
export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0