#
# Executes commands at login pre-zshrc.
#
#
## Envvars
fpath+=~/.zfunc
export EDITOR='vim'
export VISUAL='code'
export PAGER='less'
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export DOCKER_BUILDKIT=1

[ -n "$GOPATH" ] && export PATH="${PATH}:$(go env GOPATH)/bin"

eval "$(gh completion -s zsh)"
