#
# Defines environment variables.
#

# Disables loading of /etc/profile
# to avoid overriding PATH by path_helper which take cares of /etc/paths
setopt no_global_rcs

export EDITOR='vim'
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:${PATH}"
export PATH="${PATH}:/usr/local/opt/go/libexec/bin"
export PATH="${HOME}/.cargo/bin:${PATH}"

source "$HOME/.cargo/env"
