#
# Defines environment variables.
#

# Disables loading of /etc/profile
# to avoid overriding PATH by path_helper which take cares of /etc/paths
setopt no_global_rcs

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export DOCKER_BUILDKIT=1
# export PATH="${PATH}:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/ProgramData/DockerDesktop/version-bin"
# export PATH="${PATH}:/mnt/c/ProgramData/DockerDesktop/version-bin"
