# Uncomment below to enable profiling
# zmodload zsh/zprof


# Sane default
unsetopt correct_all
setopt no_beep
setopt auto_cd
export HISTFILE=~/.zsh_history
export HISTSIZE=1000000
export SAVEHIST=1000000
setopt append_history
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups # ignore duplication command history list
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_find_no_dups
setopt hist_save_no_dups
setopt hist_verify
setopt share_history
setopt inc_append_history
setopt no_auto_remove_slash
setopt interactivecomments
unsetopt menu_complete   # do not autoselect the first completion entry
unsetopt flowcontrol
setopt auto_menu         # show completion menu on succesive tab press
setopt complete_in_word
setopt always_to_end
stty stop undef
stty start undef
export WORDCHARS='*?_-.[]~=&;!#$%^(){}<>'

# Minimal settings
export ZPLUG_HOME=$HOME/.zplug
source $ZPLUG_HOME/init.zsh

# Package settings
export NVM_LAZY_LOAD=true

# Packages
zplug "b4b4r07/emoji-cli"
zplug "zsh-users/zsh-completions"
zplug "jackharrisonsherlock/common", from:github, as:theme
zplug "zsh-users/zsh-autosuggestions"
zplug "zdharma/fast-syntax-highlighting"
zplug "lukechilds/zsh-nvm"
zplug "StackExchange/blackbox"
zplug "supercrabtree/k"

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

fpath+=~/.zfunc

# Then, source plugins and add commands to $PATH
zplug load

# Completions
autoload -Uz compinit
for dump in ~/.zcompdump(N.mh+24); do
  compinit
done
compinit -C
zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]}' '+m:{[:upper:]}={[:lower:]}'

# Theming
[ -f "${HOME}/.nord.dircolors" ] && eval $(gdircolors -b ${HOME}/.nord.dircolors)
[ -n "$LS_COLORS" ] && zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

# Aliases
alias ls='ls -h --color=auto'
alias ll='ls -lh'
alias la='ls -alh'
export EDITOR="vim"
export VISUAL="vim"

# Keys, Completions
bindkey -e
bindkey "\e[Z" reverse-menu-complete
bindkey -a 'q' push-line
bindkey -a 'H' run-help
bindkey "^F" forward-char
bindkey "^B" backward-char
autoload history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey "^P" history-beginning-search-backward-end
bindkey "^N" history-beginning-search-forward-end

# Enable Ctrl-x-e to edit command line
autoload -U edit-command-line
zle -N edit-command-line
bindkey '^xe' edit-command-line
bindkey '^x^e' edit-command-line

# Functions, and utils on start-up
less_with_unbuffer () {
    unbuffer "$@" |& less -SR
}
alias ul=less_with_unbuffer

use-google-cloud-sdk () {
    export CLOUDSDK_PYTHON=python3
    _google_cloud_sdk_dir="${HOME}/google-cloud-sdk/"
    [ -f "${_google_cloud_sdk_dir}path.zsh.inc" ] && source "${_google_cloud_sdk_dir}path.zsh.inc"
    [ -f "${_google_cloud_sdk_dir}completion.zsh.inc" ] && source "${_google_cloud_sdk_dir}completion.zsh.inc"
}

activate () {
    [[ -f "./.venv/bin/activate" ]] && { source ./.venv/bin/activate ; return 0 } \
        || [[ -f "./venv/bin/activate" ]] && { source ./venv/bin/activate ; return 0 } \
        || SRC=$(echo $(dirname $(poetry run which python 2>/dev/null ) 2>/dev/null )/activate ); \
           [[ -f ${SRC} ]] && { poetry shell ; return 0 } \
        || SRC=$(echo $(dirname $(pipenv --py 2>/dev/null ) 2>/dev/null )/activate ); \
           [[ -f ${SRC} ]] && { pipenv shell ; return 0 } \
        || { echo "No virtualenv found in $(pwd)" ; return 1 }
}

# Fix for https://github.com/sdispater/poetry/issues/571 (poetry <= 0.12.*)
poetry_shell () {
    SRC=$(echo $(dirname $(poetry run which python 2>/dev/null ) 2>/dev/null )/activate )
    [[ -f ${SRC} ]] && source ${SRC} || echo "Failed to source ${SRC}"
}


count-loc () {
    find . -name "*.${1}" | xargs -L1 wc -l | tr -s " " | cut -d " " -f 2 | paste -sd+ - | bc
}


export GOPATH=$HOME/go
[[ -d "$HOME/.local" ]] && export PATH="$HOME/.local/bin:${PATH}"
if [ -d "$HOME/.pyenv" ]; then
  export PATH="$HOME/.pyenv/bin:${PATH}"
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
fi
export PATH="${PATH}:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/ProgramData/DockerDesktop/version-bin"

export PATH="${HOME}/.poetry/bin:${PATH}"
[[ -f "$HOME/ghcup/env" ]] && source "$HOME/.ghcup/env" # ghcup-env

[[ -f "${HOME}/.fzf.zsh" ]] && . ${HOME}/.fzf.zsh
export FZF_DEFAULT_OPTS="--color 16"

daemonize $(which blackd) &>/dev/null & 

export DIRENV_WARN_TIMEOUT=100s
eval "$(direnv hook zsh)"
# eval "$(anyenv init -)"

use-google-cloud-sdk

# X11
export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0

# Uncomment below to enable profiling
# zprof


#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]] && source "$SDKMAN_DIR/bin/sdkman-init.sh"

