# Path settings 
if [[ $HOST == sungrid*.naist.jp ]] || [[ $HOST == galaxy*.naist.jp ]]; then
    export WORKDIR="/nwork/$USERNAME"
    export LANG=ja_JP.UTF-8
else
    export WORKDIR="/work/$USERNAME"
fi

if [[ $HOST == pine4 ]]; then
    echo Working on pine4
    export PATH="$WORKDIR/usr/local/bin:$WORKDIR/usr/bin:${PATH}"
    export PYTHONZ_ROOT="$WORKDIR/pythonz"
    export PYTHONPATH="${PYTHONPATH}:$WORKDIR/root"
    [[ -s $WORKDIR/pythonz/etc/bashrc ]] && source $WORKDIR/pythonz/etc/bashrc
    export PATH="$WORKDIR/pythonz/pythons/CPython-2.7.3/bin:${PATH}"
    export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:$WORKDIR/root/lib"
    export SSGNC_INDEX="$WORKDIR/cl/nldata/Web1T/index/"
    export WORKON_HOME="$WORKDIR/.virtualenvs"
    export VIRTUALENVWRAPPER_PYTHON="$WORKDIR/pythonz/pythons/CPython-2.7.3/bin/python"
    export VIRTUALENVWRAPPER_VIRTUALENV="$WORKDIR/pythonz/pythons/CPython-2.7.3/bin/virtualenv"
    source $PYTHONZ_ROOT/pythons/CPython-2.7.3/bin/virtualenvwrapper.sh
elif [[ $HOST == sungrid*.naist.jp ]] || [[ $HOST == galaxy*.naist.jp ]]; then
    echo Working on sungrid
    export PATH="$WORKDIR/usr/local/bin:$WORKDIR/usr/bin:${PATH}"
    export PYTHONZ_ROOT="$WORKDIR/pythonz"
    export PYTHONPATH="${PYTHONPATH}:$WORKDIR/root"
    [[ -s $WORKDIR/pythonz/etc/bashrc ]] && source $WORKDIR/pythonz/etc/bashrc
    export PATH="$WORKDIR/pythonz/pythons/CPython-2.7.3/bin:${PATH}"
    export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:$WORKDIR/root/lib"
    export SSGNC_INDEX="$WORKDIR/cl/nldata/Web1T/index/"
    export WORKON_HOME="$WORKDIR/.virtualenvs"
    export VIRTUALENVWRAPPER_PYTHON="$WORKDIR/pythonz/pythons/CPython-2.7.3/bin/python"
    export VIRTUALENVWRAPPER_VIRTUALENV="$WORKDIR/pythonz/pythons/CPython-2.7.3/bin/virtualenv"
    source $PYTHONZ_ROOT/pythons/CPython-2.7.3/bin/virtualenvwrapper.sh
else
    echo working on $HOST
    export PATH="$HOME/usr/local/bin:$HOME/usr/bin:${PATH}"
    export PYTHONZ_ROOT="$HOME/.pythonz"
    export PYTHONPATH="${PYTHONPATH}:$HOME/root"
    [[ -s $HOME/.pythonz/etc/bashrc ]] && source $HOME/.pythonz/etc/bashrc
    export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:$HOME/root/lib"
    export WORKON_HOME="$HOME/.virtualenvs"
    export VIRTUALENVWRAPPER_PYTHON="$HOME/pythonz/pythons/CPython-2.7.3/bin"
fi

export PATH="${PATH}:$HOME/usr/local/irstlm-5.70.04/bin"
export RASP="$HOME/usr/local/rasp3os"
export STANFORD_PARSER_HOME="$HOME/usr/local/stanford-parser-2011-09-14"
export JAVA_HOME="/usr/lib64/jvm/default-java/"
export IRSTLM="$HOME/usr/local/irstlm-5.70.04"
export LD_LIBRARY_PATH="$HOME/root/lib:$HOME/usr/local/irstlm-5.70.04/lib"
export FANSEPARSER="$WORKDIR/Research/tools/fanseparser/"

export PIP_VIRTUALENV_BASE=$WORKON_HOME
PIP_RESPECT_VIRTUALENV=true
